- name: Setting macOS environment
  hosts: local
  environment:
    PATH: "{{ ansible_env.PATH }}:~/.local/bin"
  roles:
    # - core
    - zsh
    - git
    # - python
    # - java
    - javascript
    # - utilities
