- name: install pyenv python environment
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

- name: install brew python
  community.general.homebrew:
    name:
      - python
    state: present

- name: install pyenv
  community.general.homebrew:
    name:
      - pyenv
    state: present
