- include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: post-install fzf
  shell: "$(brew --prefix)/opt/fzf/install"

- name: make zsh.d
  file:
    path: ${HOME}/.zsh.d
    state: directory

- name: link zsh configs
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "${HOME}/{{ item }}"
    state: link
    force: true
  loop:
    - .zprofile
    - .zshenv
    - .zshrc
    - .p10k.zsh
    - .zsh.d

- name: install zinit
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/doc/install.sh)"
    creates: ~/.zinit/bin/zinit.zsh
