- name: install zsh from brew
  community.general.homebrew:
    name:
      - fzf
      - zsh
      - zsh-completions

- name: post-install fzf
  shell: "$(brew --prefix)/opt/fzf/install"

- name: get current shell
  command: dscl . -read /Users/${USER} UserShell
  register: current_shell

- name: switch to brew zsh
  command: sudo dscl . -create /Users/${USER} UserShell /usr/local/bin/zsh
  when: "current_shell.stdout != 'UserShell: /usr/local/bin/zsh'"

- name: make zsh.d
  file:
    path: ${HOME}/.zsh.d
    state: directory

- name: link zsh configs
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "${HOME}/{{ item }}"
    state: link
    force: true
  loop:
    - .zprofile
    - .zshenv
    - .zshrc
    - .p10k.zsh

- name: install zinit
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
    creates: ~/.zinit/bin/zinit.zsh
