- include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

#- name:
#  shell: >
#    nvm install node
#    nvm use node
#  tags:
#    - always
#
#- name: update npm
#  command: nvm install-latest-npm
#  tags:
#    - always

- name: install yarn
  community.general.npm:
    name: yarn
    global: yes
    version: "1.22.15"

- name: install global npm packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop:
    - prettier
    - npm-upgrade
    - typescript

- name: link eslint configs
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "${HOME}/{{ item }}"
    state: link
    force: true
  loop:
    - .eslintrc

